version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "05092006"
      MYSQL_DATABASE: flowboard
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flowboard-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - flowboard-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowboard_gateway?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05092006
    depends_on:
      - eureka-server
    networks:
      - flowboard-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowboard_auth?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05092006
      - APP_FRONTEND_URL=http://localhost:4200
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    networks:
      - flowboard-network

  workspace-service:
    build: ./workspace-service
    container_name: workspace-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowboard_workspace?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05092006
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    networks:
      - flowboard-network

  board-service:
    build: ./board-service
    container_name: board-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowboard_board?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05092006
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    networks:
      - flowboard-network

  list-service:
    build: ./list-service
    container_name: list-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowboard_list?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05092006
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    networks:
      - flowboard-network

  card-service:
    build: ./card-service
    container_name: card-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowboard_card?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05092006
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    networks:
      - flowboard-network

  comment-service:
    build: ./comment-service
    container_name: comment-service
    ports:
      - "8086:8086"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowboard_comment?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05092006
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    networks:
      - flowboard-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8088:8088"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowboard_notification?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05092006
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    networks:
      - flowboard-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8089:8089"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flowboard_payment?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=05092006
    depends_on:
      - eureka-server
      - gateway-service
      - mysql
    networks:
      - flowboard-network

volumes:
  mysql_data:
    driver: local

networks:
  flowboard-network:
    driver: bridge
