spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql://localhost:3306/flowboard_gateway?createDatabaseIfNotExist=true
    username: root
    password: 05092006
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: eureka-dashboard
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: auth-service-all
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/login/**,/oauth2/**
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/boards/**
        - id: list-service
          uri: lb://list-service
          predicates:
            - Path=/api/lists/**
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/cards/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
        - id: workspace-service
          uri: lb://workspace-service
          predicates:
            - Path=/api/workspaces/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true