spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql://localhost:3306/flowboard_gateway?createDatabaseIfNotExist=true
    username: root
    password: 05092006
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /api/admin/**
        - id: auth-service-oauth2
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**, /login/**
        - id: workspace-service
          uri: lb://workspace-service
          predicates:
            - Path=/api/workspaces/**
          filters:
            - Authentication
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/boards/**
          filters:
            - Authentication
        - id: list-service
          uri: lb://list-service
          predicates:
            - Path=/api/lists/**
          filters:
            - Authentication
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/cards/**
          filters:
            - Authentication
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
          filters:
            - Authentication
        - id: label-service
          uri: lb://board-service
          predicates:
            - Path=/api/labels/**
          filters:
            - Authentication
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - Authentication
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - Authentication
        - id: notification-websocket
          uri: lb://notification-service
          predicates:
            - Path=/ws/**

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true